export const MISSING_VALUE_ISSUE_MIN_RATIO = 0.01;
export const MISSING_VALUE_MEDIUM_RATIO = 0.1;
export const MISSING_VALUE_HIGH_RATIO = 0.3;
export const MISSING_VALUE_CRITICAL_RATIO = 0.75;

export const DUPLICATE_ROWS_MIN_RATIO = 0.01;
export const DUPLICATE_ROWS_HIGH_RATIO = 0.1;
export const DUPLICATE_ROWS_CRITICAL_RATIO = 0.35;

export const CONSTANT_COLUMN_MIN_NON_MISSING = 2;

export const HIGH_CARDINALITY_MIN_ROWS = 20;
export const HIGH_CARDINALITY_MIN_UNIQUE = 20;
export const HIGH_CARDINALITY_MIN_RATIO = 0.8;

export const MIXED_TYPES_MIN_RATIO = 0.01;
export const MIXED_TYPES_HIGH_RATIO = 0.1;

export const NUMERIC_OUTLIER_MIN_SAMPLE_SIZE = 8;
export const NUMERIC_OUTLIER_HIGH_RATIO = 0.1;

export const CATEGORY_COLLISION_MIN_COUNT = 1;
export const DATE_CONSISTENCY_MIN_VALUES = 3;
export const DATE_CONSISTENCY_DOMINANT_RATIO = 0.6;
export const WHITESPACE_ANOMALY_MIN_RATIO = 0.01;
